"""
v0.2.0 — the scenarios that make the app usable, not only correct.

Every requirement had a domain scenario, and the app built from v0.1.3 had
59 use cases, no HTTP route and no screen: a scenario that never says "POST"
or "taps" is satisfied without either. So each use case a person drives gets
an API scenario (the contract the mobile app calls) and, when a field actor
drives it from the phone, a screen scenario. Office, supervisor and
administrator use cases get the API only, for now.

Tuples are (requirement index, use case index, title, [given, when, then]),
like PACKS[...]["scenarios"]. Screen text is Spanish: the crews are.
"""

API_UI_SCENARIOS = {
    "time-attendance": [
        (1, 1, "API: a clock in outside the geofence is refused with the distance",
         ["a signed-in worker assigned to jobsite \"Mission Bay Tower\" whose 100 m geofence is centered at 37.7706, -122.3915",
          "they POST /api/attendance/punches with type \"in\", latitude 37.77285, longitude -122.3915 and accuracy 10",
          "the response is 422 with error \"outside_geofence\" and distanceMeters 250"]),
        (1, 1, "Screen: the worker clocks in from the home screen",
         ["a signed-in worker on the home screen whose location is 40 m from the center of jobsite \"Mission Bay Tower\"",
          "they tap \"Marcar entrada\"",
          "the screen shows \"Entrada registrada\" and the app sent a punch of type \"in\" with that location"]),
        (2, 2, "API: a clock out outside the geofence is accepted with a flag",
         ["a signed-in worker clocked in at jobsite \"Mission Bay Tower\"",
          "they POST /api/attendance/punches with type \"out\" from 400 m outside the geofence",
          "the response is 201 and the punch has the flags [\"OUTSIDE_GEOFENCE\"]"]),
        (2, 2, "Screen: a clock out outside the jobsite says a supervisor will review it",
         ["a signed-in worker clocked in, whose location is 400 m outside the geofence",
          "they tap \"Marcar salida\"",
          "the screen shows \"Salida registrada — fuera de la obra, la revisará tu supervisor\""]),
        (5, 3, "API: offline punches sync with their reconstructed times",
         ["a signed-in worker whose device holds 2 punches captured offline",
          "the device POSTs them to /api/attendance/punches/sync",
          "the response is 200 with 2 accepted punches, each with a reconstructedAt"]),
        (5, 3, "Screen: the app tells the worker its offline punches were sent",
         ["a signed-in worker with 2 punches waiting on the device",
          "the app opens with the network back",
          "the screen shows \"2 marcas sincronizadas\""]),
        (7, 4, "API: a supervisor rejects a flagged punch",
         ["a signed-in supervisor and a clock-out flagged OUTSIDE_GEOFENCE from one of their crews",
          "they POST /api/attendance/punches/{id}/review with decision \"REJECTED\" and reason \"Left site at 15:10 per GC log\"",
          "the response is 200 and GET /api/attendance/flagged no longer lists that punch"]),
        (8, 5, "API: an adjustment cannot be approved by its author",
         ["a signed-in supervisor who POSTed an adjustment of +15 minutes with reason \"Forgot to clock out\"",
          "the same supervisor POSTs /api/attendance/adjustments/{id}/approve",
          "the response is 403 with error \"approver_must_differ\""]),
        (9, 6, "API: a geofence radius outside 30–1000 m is refused",
         ["a signed-in administrator and jobsite \"Mission Bay Tower\"",
          "they PUT /api/jobsites/{id}/geofence with radiusMeters 20",
          "the response is 422 with error \"radius_out_of_range\""]),
        (10, 7, "API: a worker reads the day's hours",
         ["a signed-in worker with 8.0 approved hours and a pending adjustment of +15 minutes on 2026-11-03",
          "they GET /api/attendance/me/hours?date=2026-11-03",
          "the response is 200 with approvedHours 8.0 and pendingHours 0.25"]),
        (10, 7, "Screen: a worker sees the day's hours",
         ["a signed-in worker with 8.0 approved hours and 0.25 pending hours on 2026-11-03",
          "they open \"Mis horas\" for that day",
          "the screen shows \"8.0 h\" and \"0.25 h pendiente\""]),
        (11, 8, "API: the payroll export is CSV and reports held-back rows",
         ["a signed-in administrator and a pay period with 3 approved rows and 1 row with an unresolved flag",
          "they GET /api/timesheets/export?periodStart=2026-11-01&periodEnd=2026-11-15",
          "the response is 200 text/csv with a header and 3 data rows, and the header X-Held-Back-Rows is 1"]),
    ],
    "job-files": [
        (1, 1, "API: a job number is unique",
         ["a signed-in administrator and an existing job file \"GSR-2417\"",
          "they POST /api/job-files with job number \"GSR-2417\"",
          "the response is 409 with error \"job_number_taken\""]),
        (2, 2, "API: a photo is stored on the job file",
         ["a signed-in worker on job \"GSR-2417\"",
          "they POST /api/job-files/GSR-2417/photos with an image and the caption \"Rebar mat Level 3\"",
          "the response is 201 with the photo's takenAt, location and caption"]),
        (2, 2, "Screen: a worker adds a photo to the job",
         ["a signed-in worker on the job screen of \"GSR-2417\"",
          "they tap \"Agregar foto\", take a photo and write \"Rebar mat Level 3\"",
          "the screen shows \"Foto guardada\" and the photo appears in the job's list"]),
        (3, 3, "API: a JHA is filed with the crew's signatures",
         ["a signed-in foreman on job \"GSR-2417\"",
          "they POST /api/job-files/GSR-2417/jha with tasks, hazards, controls and 4 signatures for 2026-11-03",
          "the response is 201 and GET /api/job-files/GSR-2417/jha?date=2026-11-03 returns it"]),
        (3, 3, "Screen: a foreman files today's JHA",
         ["a signed-in foreman on the JHA screen of job \"GSR-2417\"",
          "they fill tasks, hazards and controls, collect 4 signatures and tap \"Firmar y guardar\"",
          "the screen shows \"JHA guardado\""]),
        (4, 4, "API: a failed inspection takes the forklift out of service",
         ["a signed-in operator and forklift \"FL-07\" in service",
          "they POST /api/forklifts/FL-07/inspections with \"brakes\" failed",
          "the response is 201 and GET /api/forklifts/FL-07 returns status \"OUT_OF_SERVICE\""]),
        (4, 4, "Screen: the operator sees the forklift taken out of service",
         ["a signed-in operator on the inspection screen of forklift \"FL-07\"",
          "they mark \"Frenos\" as failed and tap \"Enviar inspección\"",
          "the screen shows \"Montacargas fuera de servicio\""]),
        (5, 5, "API: a tailgate meeting records its attendees",
         ["a signed-in foreman on job \"GSR-2417\"",
          "they POST /api/job-files/GSR-2417/tailgate-meetings with topic \"Working near rebar caps\" and 3 signatures",
          "the response is 201 with 3 attendees"]),
        (5, 5, "Screen: a foreman records a tailgate meeting",
         ["a signed-in foreman on the tailgate screen of job \"GSR-2417\"",
          "they enter the topic \"Working near rebar caps\", collect 3 signatures and tap \"Guardar reunión\"",
          "the screen shows \"Reunión registrada — 3 asistentes\""]),
        (6, 6, "API: a meal break is started and ended",
         ["a signed-in worker on job \"GSR-2417\"",
          "they POST /api/breaks with type \"meal\" at 11:30 and POST /api/breaks/{id}/end at 12:00",
          "the end response is 200 with durationMinutes 30"]),
        (6, 6, "Screen: a worker takes a meal break",
         ["a signed-in worker on the home screen at 11:30",
          "they tap \"Iniciar comida\" and, at 12:00, \"Terminar comida\"",
          "the screen shows \"Comida: 30 min\""]),
        (9, 7, "API: the office searches a job file",
         ["a signed-in office user and job file \"GSR-2417\" with 2 JHAs and 1 forklift inspection on 2026-11-03",
          "they GET /api/job-files/GSR-2417/search?type=JHA&date=2026-11-03",
          "the response is 200 with exactly 2 results"]),
    ],
    "foreman-log": [
        (1, 1, "API: a log entry carries the server's capture data",
         ["a signed-in foreman on job \"GSR-2417\"",
          "they POST /api/foreman-log/entries with 2 photos and the note \"Pump truck arrived 07:40\"",
          "the response is 201 with capturedAt, location and 2 photos"]),
        (1, 1, "Screen: a foreman logs an entry with photos",
         ["a signed-in foreman on the log screen",
          "they tap \"Nueva entrada\", add 2 photos and the note \"Pump truck arrived 07:40\" and tap \"Guardar\"",
          "the screen shows \"Entrada guardada\" and the entry at the top of the list"]),
        (2, 2, "API: an audio note over 5 minutes is refused",
         ["a signed-in foreman and a log entry",
          "they POST /api/foreman-log/entries/{id}/audio with a recording of 6 minutes",
          "the response is 422 with error \"audio_too_long\""]),
        (2, 2, "Screen: a foreman records an audio note",
         ["a signed-in foreman on a log entry",
          "they tap \"Grabar nota\", speak for 1 minute 20 seconds and tap \"Detener\"",
          "the screen shows \"Nota de audio guardada (1:20)\""]),
        (3, 3, "API: revising an entry keeps the original",
         ["a signed-in foreman and a log entry with the note \"Pump truck arrived 07:40\"",
          "they PATCH /api/foreman-log/entries/{id} with the note \"Pump truck arrived 07:50\"",
          "the response is 200 with revision 2, and GET /api/foreman-log/entries/{id}/history returns both versions"]),
        (5, 4, "API: an entry is exported as a PDF",
         ["a signed-in office user and a log entry with 2 photos",
          "they GET /api/foreman-log/entries/{id}/evidence.pdf",
          "the response is 200 with content type application/pdf"]),
    ],
    "daily-reports": [
        (1, 1, "API: a new report comes prefilled",
         ["a signed-in foreman and a crew of 6 that clocked 48 hours at job \"GSR-2417\" on 2026-11-03",
          "they POST /api/daily-reports with job \"GSR-2417\" and date 2026-11-03",
          "the response is 201 with 6 workers and 48 hours"]),
        (1, 1, "Screen: a foreman opens today's report prefilled",
         ["a signed-in foreman whose crew of 6 clocked 48 hours today",
          "they tap \"Reporte del día\"",
          "the screen shows \"6 trabajadores\" and \"48 h\""]),
        (3, 2, "API: a delay is added to the report",
         ["a signed-in foreman and a draft report",
          "they PATCH /api/daily-reports/{id} adding a delay of 90 minutes caused by \"Concrete pump late\"",
          "the response is 200 and the report's delays contain that delay"]),
        (3, 2, "Screen: a foreman adds a delay",
         ["a signed-in foreman on a draft report",
          "they tap \"Agregar retraso\", enter 90 minutes and \"Concrete pump late\" and tap \"Guardar\"",
          "the screen lists \"Retraso: 90 min — Concrete pump late\""]),
        (4, 3, "API: a submitted report is locked",
         ["a signed-in foreman and a completed report",
          "they POST /api/daily-reports/{id}/submit and then PATCH /api/daily-reports/{id}",
          "the submit response is 200 with status \"SUBMITTED\" and the PATCH response is 409 with error \"report_locked\""]),
        (4, 3, "Screen: a foreman submits the report",
         ["a signed-in foreman on a completed report with 2 recipients",
          "they tap \"Enviar reporte\"",
          "the screen shows \"Reporte enviado a 2 destinatarios\" and no edit button"]),
        (5, 4, "API: an amendment keeps the submitted report",
         ["a signed-in foreman and a submitted report",
          "they POST /api/daily-reports/{id}/amendments with the reason \"Wrong delay cause\"",
          "the response is 201 and GET /api/daily-reports/{id} still returns the original content"]),
    ],
    "ai-communication": [
        (1, 1, "API: an email is explained in Spanish",
         ["a signed-in user",
          "they POST /api/communication/explain with an English email asking for revised Level 3 shop drawings by Friday 11/7",
          "the response is 200 with a Spanish explanation that names the deadline \"viernes 7 de noviembre\""]),
        (1, 1, "Screen: a user gets an email explained",
         ["a signed-in user on the email assistant screen",
          "they paste an English email and tap \"Explicar\"",
          "the screen shows the Spanish explanation"]),
        (2, 2, "API: a reply is drafted, never sent",
         ["a signed-in user",
          "they POST /api/communication/replies with the instruction \"dile que mandamos los planos el jueves\"",
          "the response is 200 with an English draft and status \"DRAFT\", and no endpoint sends it"]),
        (2, 2, "Screen: a drafted reply can be copied, not sent",
         ["a signed-in user on the email assistant screen",
          "they write \"dile que mandamos los planos el jueves\" and tap \"Redactar respuesta\"",
          "the screen shows the English draft with a \"Copiar\" button and no \"Enviar\" button"]),
    ],
    "learning": [
        (1, 1, "API: the course catalogue in Spanish",
         ["a signed-in foreman",
          "they GET /api/courses?lang=es",
          "the response is 200 and every course has a Spanish title"]),
        (1, 1, "Screen: a foreman browses the courses",
         ["a signed-in foreman with the app in Spanish",
          "they open \"Cursos\"",
          "the screen lists the courses with their Spanish titles and progress"]),
        (2, 2, "API: completing a lesson moves the progress",
         ["a signed-in foreman who completed 3 of 5 lessons of \"Rebar color coding\"",
          "they POST /api/enrollments/{id}/lessons/{lessonId}/complete for the fourth lesson",
          "the response is 200 with 4 of 5 lessons completed"]),
        (2, 2, "Screen: a lesson question gives feedback",
         ["a signed-in foreman on a lesson section with a question",
          "they tap the correct answer",
          "the screen shows \"Correcto\" and enables \"Siguiente\""]),
        (3, 3, "API: a quiz is scored",
         ["a signed-in foreman enrolled in \"Rebar basics\"",
          "they POST /api/enrollments/{id}/quiz with 8 correct answers out of 10",
          "the response is 200 with score 80 and passed true"]),
        (3, 3, "Screen: a foreman sees the quiz result",
         ["a signed-in foreman who answered the quiz of \"Rebar basics\" with 8 of 10 correct",
          "they tap \"Enviar respuestas\"",
          "the screen shows \"80% — aprobado\""]),
        (5, 5, "API: the tonnage calculator",
         ["a signed-in foreman",
          "they POST /api/calculators/tonnage with 120 bars #5 of 20 ft and 40 bars #8 of 30 ft",
          "the response is 200 with totalPounds 5707 and shortTons 2.85"]),
        (5, 5, "Screen: a foreman calculates tonnage",
         ["a signed-in foreman on the tonnage calculator",
          "they add 120 bars #5 of 20 ft and 40 bars #8 of 30 ft and tap \"Calcular\"",
          "the screen shows \"5,707 lb (2.85 tons)\""]),
        (8, 6, "API: the plan reader cites the sheet",
         ["a signed-in foreman who uploaded plan sheet \"S-201\"",
          "they POST /api/plan-reader/questions with \"What bar size is called for in the grade beams?\"",
          "the response is 200 with an answer that references \"S-201\" and a warning to check the stamped drawings"]),
        (8, 6, "Screen: a plan reader answer shows the warning",
         ["a signed-in foreman on the plan reader with sheet \"S-201\"",
          "they ask \"What bar size is called for in the grade beams?\"",
          "the screen shows the answer and the banner \"Verifica con los planos estructurales sellados\""]),
    ],
}
