"""
The domain knowledge of the Golden State Reinforcing app, as data.

`tools/build_packs.py` renders each entry into `<pack>/backend/` — pack.yaml,
a capability spec carrying every requirement's prose, and one Gherkin template
per scenario. Edit the data here, never the generated files.

Id ranges are disjoint per pack (1xx, 2xx, …) so packs compose in one project:
two packs both numbering REQ-001 collide in the traceability matrix.
"""

PACKS = [
    # ── 1. Time & attendance ────────────────────────────────────────────────
    {
        "slug": "time-attendance",
        "name": "Time & Attendance",
        "range": 1,
        "summary": "Geofenced clock in / clock out that resists manipulation, works offline, and leaves an audit trail payroll can trust.",
        "contexts": [
            ("Attendance", "Core", "Punches, shifts and timesheets", ["Punch", "Timesheet"]),
            ("Jobsites", "Supporting", "Jobsites and their geofences", ["Jobsite"]),
        ],
        "requirements": [
            ("Clock in only inside the assigned jobsite's geofence", "Must", "functional",
             "A worker can clock in only when the device's location fix lies inside the geofence of a jobsite they are assigned to. Outside it, the clock-in is refused and the worker is told how far away they are."),
            ("Clock out from anywhere, flagging punches outside the geofence", "Must", "functional",
             "A worker can always clock out — refusing it would inflate hours — but a clock-out whose fix lies outside the jobsite geofence is recorded with the flag OUTSIDE_GEOFENCE for supervisor review."),
            ("Every punch is immutable and carries its evidence", "Must", "business-rule",
             "A punch records worker, jobsite, type (in/out), device time, server receipt time, elapsed monotonic time, latitude, longitude and accuracy. Once written it is never edited; a correction is a separate adjustment record with a reason, an author and an approver."),
            ("Reject spoofed locations and compromised devices", "Must", "functional",
             "A punch whose location is reported as mocked by the OS, or that comes from a rooted or jailbroken device, is refused. A fix with accuracy worse than 100 m is accepted only with the flag LOW_ACCURACY."),
            ("Capture punches offline and sync them without trusting the device clock", "Must", "functional",
             "With no network a punch is stored on the device with its device time and the monotonic elapsed time since boot, and synced when the network returns. The server reconstructs the capture time from the monotonic clock and flags CLOCK_TAMPERED when device time and reconstructed time differ by more than 2 minutes."),
            ("Verify identity with a photo at clock in", "Should", "functional",
             "Clock-in takes a front-camera photo stored with the punch, so a supervisor can spot buddy punching. Photos are never used for automated biometric matching without written consent."),
            ("Supervisors review flagged punches", "Must", "functional",
             "A supervisor sees every flagged punch of their crews with its evidence (map, accuracy, photo, flags) and approves or rejects it with a reason. The decision is recorded, not the punch edited."),
            ("Correct a punch through an approved adjustment", "Must", "business-rule",
             "A missed or wrong punch is corrected by an adjustment that states the corrected time and a reason, entered by the worker or a supervisor and approved by someone other than its author."),
            ("Configure a geofence per jobsite", "Must", "functional",
             "An administrator defines each jobsite's geofence as a center and a radius (default 100 m, range 30–1000 m) and assigns crews to it. Changes are versioned so past punches are judged against the geofence in force when they happened."),
            ("Workers see their own hours", "Should", "functional",
             "A worker sees their punches and total hours per day and per week, including pending adjustments, in English or Spanish."),
            ("Export timesheets for payroll", "Should", "functional",
             "An administrator exports approved timesheets per pay period as CSV (worker, jobsite, date, in, out, breaks, regular and overtime hours). Unresolved flags block the export of the affected rows."),
            ("A punch is confirmed on the device within 2 seconds", "Must", "non-functional",
             "From the tap to the on-screen confirmation, online or offline, a punch completes in under 2 seconds on a mid-range Android phone."),
            ("Location is captured only at punch time", "Must", "non-functional",
             "The app reads location only while a punch is being taken. It does not track workers off shift or in the background (California privacy expectations; CCPA)."),
        ],
        "use_cases": [
            ("Clock In", "Worker", 1, "ClockInCommand", "Punch", "WorkerClockedIn"),
            ("Clock Out", "Worker", 2, "ClockOutCommand", "Punch", "WorkerClockedOut"),
            ("Sync Offline Punches", "Worker device", 5, "SyncOfflinePunchesCommand", "Punch", "PunchSynced"),
            ("Review Flagged Punch", "Supervisor", 7, "ReviewPunchCommand", "Punch", "PunchReviewed"),
            ("Adjust Punch", "Supervisor", 8, "AdjustPunchCommand", "Timesheet", "PunchAdjusted"),
            ("Configure Jobsite Geofence", "Administrator", 9, "ConfigureGeofenceCommand", "Jobsite", "GeofenceConfigured"),
            ("View My Hours", "Worker", 10, None, "Timesheet", None),
            ("Export Timesheet", "Administrator", 11, None, "Timesheet", "TimesheetExported"),
        ],
        "events": [
            ("WorkerClockedIn", "Punch", ["punchId: string", "workerId: string", "jobsiteId: string", "capturedAt: datetime", "flags: string[]"]),
            ("WorkerClockedOut", "Punch", ["punchId: string", "workerId: string", "jobsiteId: string", "capturedAt: datetime", "flags: string[]"]),
            ("PunchSynced", "Punch", ["punchId: string", "reconstructedAt: datetime", "flags: string[]"]),
            ("PunchReviewed", "Punch", ["punchId: string", "decision: string", "reviewerId: string", "reason: string"]),
            ("PunchAdjusted", "Timesheet", ["adjustmentId: string", "punchId: string", "correctedAt: datetime", "approvedBy: string"]),
            ("GeofenceConfigured", "Jobsite", ["jobsiteId: string", "version: number", "radiusMeters: number"]),
            ("TimesheetExported", "Timesheet", ["periodStart: date", "periodEnd: date", "rows: number"]),
        ],
        "rules": [
            ("A punch is never edited", "Corrections are adjustments approved by someone other than their author."),
            ("A worker may only clock in at a jobsite they are assigned to", "Assignment is checked server-side, not only in the app."),
            ("Server time decides", "The capture time of an offline punch is reconstructed from the monotonic clock, never taken from the device clock alone."),
        ],
        "scenarios": [
            (1, 1, "A clock in inside the geofence is accepted",
             ["a worker assigned to jobsite \"Mission Bay Tower\" with a 100 m geofence",
              "they clock in from 40 m away from the jobsite center with 12 m accuracy",
              "the punch is recorded as accepted with no flags"]),
            (1, 1, "A clock in outside the geofence is refused",
             ["a worker assigned to jobsite \"Mission Bay Tower\" with a 100 m geofence",
              "they clock in from 650 m away",
              "the clock in is refused and the worker is told they are 550 m outside the jobsite"]),
            (4, 1, "A clock in from a mocked location is refused",
             ["a worker inside the geofence of their jobsite",
              "they clock in and the OS reports the location as mocked",
              "the clock in is refused with the reason MOCK_LOCATION"]),
            (5, 3, "An offline punch keeps its real capture time",
             ["a worker clocked in offline at 07:02 by the monotonic clock",
              "the punch is synced at 09:15 with the device clock set to 06:30",
              "the punch is stored at 07:02 with the flag CLOCK_TAMPERED"]),
            (2, 2, "A clock out outside the geofence is flagged, not refused",
             ["a worker clocked in at jobsite \"Mission Bay Tower\"",
              "they clock out from 2 km away",
              "the clock out is recorded with the flag OUTSIDE_GEOFENCE"]),
            (8, 5, "A correction is an adjustment, never an edit",
             ["a worker who forgot to clock out at 15:30",
              "their supervisor adjusts the punch to 15:30 with the reason \"forgot to clock out\" and another supervisor approves it",
              "the original punch is unchanged and the timesheet shows the adjusted time with its approval"]),
            (3, 1, 'Every punch carries its evidence and cannot be edited',
             ['a worker inside the geofence of jobsite "Mission Bay Tower"', 'they clock in and someone later tries to change the punch time', 'the punch keeps its device time, server time, monotonic time, latitude, longitude and accuracy, and the change is refused']),
            (6, 1, "Clock in takes an identity photo",
             ["a worker clocking in at their jobsite", "the clock in completes", "a front-camera photo is attached to the punch"]),
            (12, 1, "A punch is confirmed in under 2 seconds offline",
             ["a worker with no network inside their jobsite's geofence", "they tap clock in", "the confirmation is on screen in under 2 seconds"]),
            (13, 2, "No location is read off shift",
             ["a worker who clocked out at 15:30", "the app stays open in the background until 17:00", "no location reading is taken after the clock out"]),
        ],
    },
    # ── 2. Job files ────────────────────────────────────────────────────────
    {
        "slug": "job-files",
        "name": "Job Files",
        "range": 2,
        "summary": "One digital file per job: daily photos, safety records (JHA, forklift inspections, tailgate meetings) and break tracking, filled in from each worker's phone.",
        "contexts": [
            ("JobFile", "Core", "The job's file and everything filed in it", ["JobFile"]),
            ("Safety", "Core", "Daily safety records", ["SafetyRecord"]),
            ("Breaks", "Supporting", "Meal and rest periods", ["BreakLog"]),
        ],
        "requirements": [
            ("Create a digital file per job", "Must", "functional",
             "An administrator creates a job file with the job number, name, address, general contractor and start date. Every record below belongs to exactly one job file."),
            ("Take and store jobsite photos", "Must", "functional",
             "A worker takes photos of the jobsite and the day's progress from the app; each is stored with the job, author, timestamp and location, and is available to the office within minutes of the phone regaining network."),
            ("Record a daily Job Hazard Analysis (JHA)", "Must", "functional",
             "Before work starts, the crew's JHA is filled in: tasks, hazards, controls and the signatures of every worker on the crew. A day without a JHA is visible on the job file."),
            ("Record forklift inspections", "Must", "functional",
             "A pre-shift forklift inspection checklist (Cal/OSHA) is completed per forklift and day. A failed item marks the forklift out of service until a corrective note is filed."),
            ("Record tailgate safety meetings", "Must", "functional",
             "A tailgate meeting records topic, date, presenter and attendees' signatures, and can attach a photo of the sign-in sheet."),
            ("Track meal and rest breaks precisely", "Must", "functional",
             "A worker starts and ends meal and rest breaks from the app; each break records start, end and location, and the day's breaks appear on the timesheet."),
            ("Warn before a meal period is due", "Should", "business-rule",
             "Under California rules a 30-minute meal period starts before the end of the 5th hour worked, and a second before the end of the 10th. The app reminds the worker at 4h30m and records a missed or late meal period for the office. A covering collective bargaining agreement may change this; the thresholds are configurable."),
            ("Every worker files from their own phone", "Must", "non-functional",
             "All job-file actions work from the worker's own Android or iPhone, offline included, with records queued and synced; everything is archived centrally."),
            ("Search a job file", "Should", "functional",
             "The office finds any record in a job file by date, type, author or text."),
        ],
        "use_cases": [
            ("Open Job File", "Administrator", 1, "OpenJobFileCommand", "JobFile", "JobFileOpened"),
            ("Add Jobsite Photo", "Worker", 2, "AddPhotoCommand", "JobFile", "PhotoAdded"),
            ("File JHA", "Foreman", 3, "FileJhaCommand", "SafetyRecord", "JhaFiled"),
            ("Inspect Forklift", "Operator", 4, "InspectForkliftCommand", "SafetyRecord", "ForkliftInspected"),
            ("Hold Tailgate Meeting", "Foreman", 5, "RecordTailgateCommand", "SafetyRecord", "TailgateRecorded"),
            ("Take Break", "Worker", 6, "TakeBreakCommand", "BreakLog", "BreakTaken"),
            ("Search Job File", "Office", 9, None, "JobFile", None),
        ],
        "events": [
            ("JobFileOpened", "JobFile", ["jobFileId: string", "jobNumber: string"]),
            ("PhotoAdded", "JobFile", ["photoId: string", "jobFileId: string", "takenAt: datetime"]),
            ("JhaFiled", "SafetyRecord", ["jhaId: string", "jobFileId: string", "date: date", "signatures: number"]),
            ("ForkliftInspected", "SafetyRecord", ["inspectionId: string", "forkliftId: string", "passed: boolean"]),
            ("TailgateRecorded", "SafetyRecord", ["meetingId: string", "topic: string", "attendees: number"]),
            ("BreakTaken", "BreakLog", ["breakId: string", "kind: string", "startedAt: datetime", "endedAt: datetime"]),
        ],
        "rules": [
            ("No work without a JHA", "The job file shows any crew-day with punches but no JHA."),
            ("A failed forklift item takes the forklift out of service", "Until a corrective note is filed."),
        ],
        "scenarios": [
            (3, 3, "A crew-day without a JHA is visible on the job file",
             ["a crew that clocked in at jobsite \"Mission Bay Tower\" today",
              "no JHA has been filed for that crew today",
              "the job file shows today's JHA as missing for that crew"]),
            (4, 4, "A failed forklift item puts the forklift out of service",
             ["forklift \"FL-07\" in service",
              "the pre-shift inspection marks \"brakes\" as failed",
              "forklift \"FL-07\" is out of service until a corrective note is filed"]),
            (7, 6, "A meal period reminder comes before the fifth hour",
             ["a worker clocked in at 06:00 with no break taken",
              "it is 10:30",
              "the worker is reminded to start a 30-minute meal period before 11:00"]),
            (2, 2, "A photo taken offline reaches the job file after sync",
             ["a worker with no network at jobsite \"Mission Bay Tower\"",
              "they take a progress photo and the network returns",
              "the photo appears in the job file with its original capture time"]),
            (8, 2, "A record made offline is archived centrally",
             ["a worker with no network fills in a tailgate meeting from their own phone", "the network returns", "the meeting is archived in the job file with its original time"]),
        ],
    },
    # ── 3. Foreman log (CYB) ────────────────────────────────────────────────
    {
        "slug": "foreman-log",
        "name": "Foreman Log (CYB)",
        "range": 3,
        "summary": "The foreman's 'cover your back' log: photos, audio notes and timestamps per task or event on the job.",
        "contexts": [("ForemanLog", "Core", "Timestamped evidence entries", ["LogEntry"])],
        "requirements": [
            ("Log an entry with photos per task or event", "Must", "functional",
             "A foreman creates a log entry for a task or event (delay, instruction from the GC, damage, inspection) with one or more photos; the entry is timestamped and geolocated at capture."),
            ("Record audio notes on an entry", "Must", "functional",
             "A foreman records audio notes (up to 5 minutes each) on an entry; audio is stored with the entry and can be played from the office."),
            ("Entries are tamper-evident", "Must", "business-rule",
             "An entry's capture time, location and media hashes are fixed at capture; edits append a revision and never change the original, so the log can back a claim with the general contractor."),
            ("Transcribe audio notes", "Could", "functional",
             "Audio notes are transcribed (English and Spanish) so they can be searched and quoted."),
            ("Share an entry as evidence", "Should", "functional",
             "A foreman or the office exports an entry, or a date range of entries, as a PDF with photos, transcript, timestamps and map."),
        ],
        "use_cases": [
            ("Log Event", "Foreman", 1, "LogEventCommand", "LogEntry", "EntryLogged"),
            ("Add Audio Note", "Foreman", 2, "AddAudioNoteCommand", "LogEntry", "AudioNoteAdded"),
            ("Revise Entry", "Foreman", 3, "ReviseEntryCommand", "LogEntry", "EntryRevised"),
            ("Export Evidence", "Office", 5, None, "LogEntry", "EvidenceExported"),
        ],
        "events": [
            ("EntryLogged", "LogEntry", ["entryId: string", "jobFileId: string", "capturedAt: datetime"]),
            ("AudioNoteAdded", "LogEntry", ["entryId: string", "audioId: string", "seconds: number"]),
            ("EntryRevised", "LogEntry", ["entryId: string", "revision: number"]),
            ("EvidenceExported", "LogEntry", ["from: date", "to: date", "entries: number"]),
        ],
        "rules": [("The original entry is permanent", "Revisions append; the capture is never overwritten.")],
        "scenarios": [
            (3, 3, "Revising an entry keeps the original capture",
             ["a log entry captured at 08:14 with two photos",
              "the foreman revises its description at 16:00",
              "the entry shows revision 2 and the original capture time, photos and hashes are unchanged"]),
            (1, 1, "A log entry is timestamped and geolocated at capture",
             ["a foreman at jobsite \"Mission Bay Tower\"",
              "they log \"GC instructed to hold pour on level 3\" with a photo",
              "the entry carries the capture time and location of the photo"]),
            (4, 2, 'An audio note in Spanish is transcribed',
             ['a foreman records the audio note "el GC pidió parar el colado del nivel 3"', 'the transcription completes', 'the entry shows the Spanish transcript and is found by searching "nivel 3"']),
        ],
    },
    # ── 4. Daily reports ────────────────────────────────────────────────────
    {
        "slug": "daily-reports",
        "name": "Daily Reports",
        "range": 4,
        "summary": "A daily job report the foreman finishes in minutes, prefilled from the day's punches, photos, safety records and log.",
        "contexts": [("DailyReport", "Core", "The daily report per job", ["DailyReport"])],
        "requirements": [
            ("Prefill the daily report from the day's records", "Must", "functional",
             "The report for a job and day is prefilled with crew and hours (from punches), photos, safety records and log entries, so the foreman only reviews and adds what is missing."),
            ("Finish a daily report in under 5 minutes", "Must", "non-functional",
             "A foreman with a normal day completes and submits the report in under 5 minutes, measured in the pilot."),
            ("Add work done, delays and materials", "Must", "functional",
             "The foreman adds work completed, delays with their cause, materials received and equipment on site, in English or Spanish."),
            ("Submit and share the report", "Must", "functional",
             "A submitted report is locked, stored in the job file and sent as PDF to configured recipients (office, PM)."),
            ("A submitted report is never edited", "Must", "business-rule",
             "Changes after submission create an amendment linked to the original."),
        ],
        "use_cases": [
            ("Draft Daily Report", "Foreman", 1, "DraftReportCommand", "DailyReport", "ReportDrafted"),
            ("Complete Report Details", "Foreman", 3, "CompleteReportCommand", "DailyReport", None),
            ("Submit Daily Report", "Foreman", 4, "SubmitReportCommand", "DailyReport", "ReportSubmitted"),
            ("Amend Daily Report", "Foreman", 5, "AmendReportCommand", "DailyReport", "ReportAmended"),
        ],
        "events": [
            ("ReportDrafted", "DailyReport", ["reportId: string", "jobFileId: string", "date: date"]),
            ("ReportSubmitted", "DailyReport", ["reportId: string", "submittedAt: datetime"]),
            ("ReportAmended", "DailyReport", ["reportId: string", "amendmentId: string"]),
        ],
        "rules": [("One report per job and day", "A second report for the same job and day is an amendment.")],
        "scenarios": [
            (1, 1, "The report starts prefilled from the day",
             ["a crew of 6 that clocked 48 hours at jobsite \"Mission Bay Tower\" today with 12 photos and a JHA",
              "the foreman opens today's report",
              "the report lists the 6 workers, 48 hours, 12 photos and the JHA"]),
            (5, 4, "Changing a submitted report creates an amendment",
             ["today's report submitted at 17:10",
              "the foreman changes the delay cause at 18:00",
              "an amendment is created and the submitted report is unchanged"]),
            (2, 1, "A normal day's report is finished in under 5 minutes",
             ["a prefilled report for a normal day", 'the foreman adds "rebar placed for level 3 deck" and the delay "pump truck 45 min late"', "the report is submitted less than 5 minutes after it was opened"]),
        ],
    },
    # ── 5. AI communication assistant ───────────────────────────────────────
    {
        "slug": "ai-communication",
        "name": "AI Communication Assistant",
        "range": 5,
        "summary": "Helps Spanish-speaking staff read and answer English email correctly, with the person always deciding what is sent.",
        "contexts": [("Communication", "Supporting", "Email understanding and drafting", ["EmailDraft"])],
        "requirements": [
            ("Explain an English email in Spanish", "Must", "functional",
             "A user pastes or forwards an English email and gets a faithful Spanish explanation: who asks what, by when, and what is expected of them."),
            ("Draft a reply in correct professional English", "Must", "functional",
             "From what the user says in Spanish (typed or dictated), the assistant drafts a professional English reply, shown side by side with its Spanish back-translation."),
            ("The user always sends, never the AI", "Must", "business-rule",
             "The assistant never sends email by itself. The user reviews, edits and sends from their own mail client."),
            ("Keep construction terms precise", "Should", "functional",
             "A glossary of rebar and construction terms (RFI, submittal, T&M, tag work, pour, PT cables, rebar sizes) is applied so translations keep trade meaning."),
            ("No customer data is used to train models", "Must", "non-functional",
             "Email content is sent only to an AI provider under terms that exclude training on it, and is not stored beyond the session unless the user saves the draft."),
        ],
        "use_cases": [
            ("Explain Email", "User", 1, "ExplainEmailCommand", "EmailDraft", "EmailExplained"),
            ("Draft Reply", "User", 2, "DraftReplyCommand", "EmailDraft", "ReplyDrafted"),
        ],
        "events": [
            ("EmailExplained", "EmailDraft", ["draftId: string", "language: string"]),
            ("ReplyDrafted", "EmailDraft", ["draftId: string", "tone: string"]),
        ],
        "rules": [("A person sends every email", "The app produces drafts, never sends.")],
        "scenarios": [
            (2, 2, "A Spanish instruction becomes an English reply the user reviews",
             ["an English email from the GC asking to confirm the level 3 pour for Friday",
              "the user says \"confírmale que el viernes a las 7 estamos listos\"",
              "an English reply confirming the Friday 7:00 pour is drafted with its Spanish back-translation and is not sent"]),
            (3, 2, "The assistant never sends email",
             ["a reply drafted by the assistant", "the user closes the assistant", "no email has been sent and the draft is offered to copy into their mail client"]),
            (4, 1, 'Trade terms keep their meaning',
             ['an English email that says "Send the T&M tickets for the tag work on level 2 by Friday"', 'the user asks for an explanation', 'the Spanish explanation says "T&M (tiempo y materiales)" and "tag work (trabajo extra autorizado)"']),
            (5, 1, "Email content is not kept after the session",
             ["a user who had an email explained and saved no draft", "the session ends", "no copy of the email content remains stored by the app"]),
        ],
    },
    # ── 6. Learning ─────────────────────────────────────────────────────────
    {
        "slug": "learning",
        "name": "Foreman Learning",
        "range": 6,
        "summary": "Interactive bilingual (English/Spanish) training for foremen, with calculators and an AI plan reader.",
        "contexts": [
            ("Learning", "Core", "Courses, lessons, quizzes and progress", ["Course", "Enrollment"]),
            ("Tools", "Supporting", "Field calculators and the plan reader", ["Calculator"]),
        ],
        "requirements": [
            ("Offer a catalogue of bilingual courses", "Must", "functional",
             "Courses are published in English and Spanish; a learner switches language at any time without losing progress. The initial catalogue covers: blueprint reading vs structural plans, workload planning, avoiding crew idle time, QC before every concrete pour, working with the general contractor, crew cost, tag work and T&M, PT cable accessories, manpower planning, rates, rebar color coding, rigging and picks, personal time management, tonnage, jobsite safety, rebar weight tables, ACI 117 tolerances, the AI plan reader, heat illness prevention, sexual harassment prevention and substance abuse prevention."),
            ("Lessons are interactive", "Must", "functional",
             "A lesson combines short text, images or video, and at least one interaction (question, exercise or calculator) per section."),
            ("Quiz each course and track progress", "Must", "functional",
             "Each course ends with a quiz; the learner's progress, scores and completion dates are recorded and visible to their manager."),
            ("Compliance courses keep a certificate", "Must", "business-rule",
             "Heat illness prevention, sexual harassment prevention and substance abuse prevention issue a dated completion certificate, retained for the period the company's compliance policy sets."),
            ("Calculate rebar weight and tonnage", "Must", "functional",
             "A calculator returns weight per bar size (#3 to #18) and length, and total tonnage for a list of bars, using the standard rebar weight table."),
            ("Calculate crew cost and rates", "Should", "functional",
             "A calculator returns crew cost for a crew composition, hours and rates, including overtime."),
            ("Check against ACI 117 tolerances", "Should", "functional",
             "A tool tells whether a measured placement (cover, spacing) is within the ACI 117 tolerance for the element and dimension."),
            ("Read plans with AI assistance", "Could", "functional",
             "A foreman uploads a plan sheet and asks questions; the assistant answers with references to the sheet, and states clearly that answers must be checked against the stamped structural drawings."),
            ("Lessons work offline", "Should", "non-functional",
             "A downloaded course is usable without network; progress syncs later."),
        ],
        "use_cases": [
            ("Browse Courses", "Foreman", 1, None, "Course", None),
            ("Take Lesson", "Foreman", 2, "CompleteLessonCommand", "Enrollment", "LessonCompleted"),
            ("Take Quiz", "Foreman", 3, "SubmitQuizCommand", "Enrollment", "QuizSubmitted"),
            ("Issue Certificate", "System", 4, "IssueCertificateCommand", "Enrollment", "CertificateIssued"),
            ("Calculate Rebar Tonnage", "Foreman", 5, None, "Calculator", None),
            ("Ask Plan Reader", "Foreman", 8, "AskPlanQuestionCommand", "Calculator", "PlanQuestionAnswered"),
        ],
        "events": [
            ("LessonCompleted", "Enrollment", ["enrollmentId: string", "lessonId: string"]),
            ("QuizSubmitted", "Enrollment", ["enrollmentId: string", "score: number"]),
            ("CertificateIssued", "Enrollment", ["certificateId: string", "courseId: string", "issuedAt: date"]),
            ("PlanQuestionAnswered", "Calculator", ["questionId: string", "sheet: string"]),
        ],
        "rules": [("Language never resets progress", "Progress belongs to the course, not to its language.")],
        "scenarios": [
            (5, 5, "Tonnage of a bar list",
             ["a bar list of 120 bars #5 of 20 ft and 40 bars #8 of 30 ft",
              "the foreman calculates the tonnage",
              "the total is 5,707 lb (2.85 short tons)"]),
            (1, 2, "Switching language keeps progress",
             ["a foreman who completed 3 of 5 lessons of \"Rebar color coding\" in Spanish",
              "they switch the app to English",
              "the course shows 3 of 5 lessons completed"]),
            (4, 4, "A passed compliance course issues a certificate",
             ["a foreman who passes the \"Heat illness prevention\" quiz",
              "the quiz is submitted",
              "a dated completion certificate is issued and listed on their profile"]),
            (6, 5, "Crew cost with overtime",
             ["a crew of 1 foreman at $60/h and 4 ironworkers at $50/h working 10 hours with overtime at 1.5x after 8 hours", "the foreman calculates the crew cost", "the total is $2,860"]),
            (7, 5, "Cover outside the ACI 117 tolerance",
             ["a 6 in deep member with a specified cover of 1.5 in", "the measured cover is 1.0 in", "the tool reports the cover 1/8 in outside the -3/8 in ACI 117 tolerance"]),
            (9, 2, 'A downloaded lesson works offline',
             ['a foreman who downloaded "Rebar color coding"', 'they open its next lesson with no network', 'the lesson opens and its completion syncs when the network returns']),
        ],
    },
]


# What each requirement builds on, by requirement number within its pack
# Cross-pack dependencies are not expressible yet: Specgate's depends_on
# resolves only within one pack (reported upstream). The harness stacks a requirement's
# branch on its dependencies instead of building it from the same base — built
# in parallel, REQ-101 and REQ-104 each invented their own Punch and Geofence.
DEPENDS = {
    "time-attendance": {2: [1], 3: [1], 4: [1], 5: [1], 6: [1], 7: [1], 8: [1], 10: [1], 11: [8], 12: [1], 13: [1]},
    "job-files": {2: [1], 3: [1], 4: [1], 5: [1], 7: [6], 8: [2], 9: [1]},
    "foreman-log": {2: [1], 3: [1], 4: [2], 5: [1]},
    "daily-reports": {2: [1], 3: [1], 4: [1], 5: [4]},
    "ai-communication": {2: [1], 3: [2], 4: [1], 5: [1]},
    "learning": {2: [1], 3: [2], 4: [3], 9: [2]},
}

# v0.1.3 — a scenario for every requirement that had none. Sixteen
# requirements reached the app with nothing to verify them, so `plan` put them
# under "Needs Feature File" and the harness had no `Then` to hold the agent
# to. Appended, not inserted: scenario ids are positional, and the ids the app
# already links to must not move.
MORE_SCENARIOS = {
    "time-attendance": [
        (7, 4, "A supervisor rejects a flagged punch with a reason",
         ["a clock-out flagged OUTSIDE_GEOFENCE for worker \"Luis Ortega\" on a crew the supervisor leads",
          "the supervisor rejects it with the reason \"Left site at 15:10 per GC log\"",
          "the review is recorded as REJECTED with that reason and the punch itself is unchanged"]),
        (9, 6, "A geofence change does not rejudge past punches",
         ["jobsite \"Mission Bay Tower\" with a 100 m geofence and a clock in accepted 80 m from its center",
          "an administrator reduces the geofence radius to 50 m",
          "the geofence is at version 2 and the earlier clock in is still judged against version 1 as accepted"]),
        (10, 7, "A worker sees the day's hours with a pending adjustment",
         ["a worker clocked in at 06:00 and out at 14:30 with a 30 minute meal break, and has a pending adjustment of +15 minutes",
          "they open their hours for that day in Spanish",
          "they see 8.0 approved hours and 0.25 pending hours labelled \"pendiente\""]),
        (11, 8, "An unresolved flag holds back only its own row from the export",
         ["a pay period with 3 approved timesheet rows and 1 row with an unresolved LOW_ACCURACY flag",
          "an administrator exports the period as CSV",
          "the CSV has the header row and 3 data rows, and the flagged row is reported as held back"]),
    ],
    "job-files": [
        (1, 1, "A job file is created with its identity",
         ["an administrator with job number \"GSR-2417\", name \"Mission Bay Tower\", address \"1500 Owens St, San Francisco\", general contractor \"Webcor\" and start date 2026-11-02",
          "they create the job file",
          "the job file exists with those five values and no records"]),
        (5, 5, "A tailgate meeting records who attended",
         ["a job file \"GSR-2417\" and a tailgate meeting on topic \"Working near rebar caps\" presented by foreman \"Ana Ruiz\"",
          "3 workers sign the attendance",
          "the meeting is stored on the job file with its topic, date, presenter and 3 signatures"]),
        (6, 6, "A meal break shows on the day's timesheet",
         ["a worker on job \"GSR-2417\" who starts a meal break at 11:30",
          "they end the break at 12:00",
          "the break is recorded as a 30 minute meal break with its start, end and location, and the day's timesheet lists it"]),
        (9, 7, "The office finds records by type and date",
         ["job file \"GSR-2417\" with 2 JHAs and 1 forklift inspection dated 2026-11-03, and 1 JHA dated 2026-11-04",
          "the office searches the job file for type JHA on 2026-11-03",
          "exactly the 2 JHAs from 2026-11-03 are returned"]),
    ],
    "foreman-log": [
        (2, 2, "An audio note longer than 5 minutes is refused",
         ["a foreman's log entry for 2026-11-03",
          "they attach an audio note of 5 minutes 20 seconds",
          "the note is refused with the reason that audio notes are limited to 5 minutes"]),
        (5, 4, "An entry exported as evidence carries its capture data",
         ["a log entry with 2 photos, a transcript and a capture time of 2026-11-03 07:42 at the jobsite",
          "the office exports the entry as evidence",
          "a PDF is produced that contains the 2 photos, the transcript, the capture time and the location"]),
    ],
    "daily-reports": [
        (3, 2, "A delay is recorded with its cause",
         ["a draft daily report for job \"GSR-2417\" on 2026-11-03",
          "the foreman adds a delay of 90 minutes caused by \"Concrete pump late\"",
          "the report lists the delay with 90 minutes and that cause"]),
        (4, 3, "A submitted report is locked and sent",
         ["a completed daily report for job \"GSR-2417\" with recipients office@gsr.example and pm@webcor.example",
          "the foreman submits it",
          "the report is locked, stored in the job file, and a PDF is queued for both recipients"]),
    ],
    "ai-communication": [
        (1, 1, "An English email is explained in Spanish",
         ["an English email from the general contractor asking \"Please submit the revised rebar shop drawings for Level 3 by Friday 11/7\"",
          "the user asks for an explanation",
          "the Spanish explanation names who asks, what is asked (planos de taller revisados del nivel 3) and the deadline (viernes 7 de noviembre)"]),
    ],
    "learning": [
        (2, 2, "Every lesson section has an interaction",
         ["a lesson \"Reading bar marks\" with 3 sections",
          "it is published",
          "publishing is accepted only because each of the 3 sections has at least one question, exercise or calculator"]),
        (3, 3, "A quiz result is visible to the learner's manager",
         ["a learner who completes the quiz of course \"Rebar basics\" with 8 correct answers out of 10",
          "their manager opens the team's progress",
          "the manager sees the course as completed with a score of 80% and the completion date"]),
        (8, 6, "A plan reader answer cites the sheet and carries the warning",
         ["a foreman who uploaded plan sheet \"S-201\" and asks \"What bar size is called for in the grade beams?\"",
          "the assistant answers",
          "the answer references sheet S-201 and states that it must be checked against the stamped structural drawings"]),
    ],
}
for _pack in PACKS:
    _pack["scenarios"] = _pack["scenarios"] + MORE_SCENARIOS.get(_pack["slug"], [])

# v0.2.0 — API and screen scenarios; see tools/api_ui_scenarios.py.
from api_ui_scenarios import API_UI_SCENARIOS  # noqa: E402
for _pack in PACKS:
    _pack["scenarios"] = _pack["scenarios"] + API_UI_SCENARIOS.get(_pack["slug"], [])
